In [ ]:
import torch

In [ ]:
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0,requires_grad = True)

In [ ]:
def forward(x):
  yhat = w *x +b
  return yhat

In [ ]:

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)


The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)


The shape of x:  torch.Size([2, 1])


In [ ]:
yhat = forward(x)
print("The prediction", yhat)

The prediction tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


In [ ]:
from torch.nn import Linear

In [ ]:
torch.manual_seed(1)

In [ ]:
lr = Linear(in_features=1 , out_features =1, bias = True)
print("Parameters w and b", list(lr.parameters()))

Parameters w and b [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
print("Python dictionary", lr.state_dict())
print('keys', lr.state_dict().keys())
print('values', lr.state_dict().values())

Python dictionary OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys odict_keys(['weight', 'bias'])
values odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [ ]:
print('weight', lr.weight)
print('bias', lr.bias)

weight Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias Parameter containing:
tensor([-0.4414], requires_grad=True)


In [ ]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction", yhat)

The prediction tensor([[0.0739]], grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction", yhat)

The prediction tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ", yhat)


The prediction:  tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)


In [ ]:
from torch import nn

In [ ]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super(LR, self).__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self, x):
    out = self.linear(x)
    return out

In [1]:
lr = LR(1, 1)
print('The parameters ', list(lr.parameters()))
print("Linear model", lr.linear)

NameError: name 'LR' is not defined

In [2]:
x= torch.tensor([1.0], [2.0])
yhat = lr(x)
print('The prediction ', yhat)

NameError: name 'torch' is not defined

In [ ]:
print('Python dictionary ', lr.state_dict())
print('keys', lr.state_dict().keys)
print('values', lr.state_dict().values)

In [ ]:
x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = lr(x)
print("The prediction", yhat)

In [3]:
!git init


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [5]:
!git init Prediction-Regression-Pytorch


hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/Prediction-Regression-Pytorch/.git/


In [8]:
!git add .

error: 'Prediction-Regression-Pytorch/' does not have a commit checked out
fatal: adding files failed


In [9]:
!git commit -m "Initial commit"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@5704807fe35c.(none)')


In [11]:
!git config --global user.email "jaylim070@gmail.com"

In [12]:
!git branch -a

In [13]:
!git checkout

fatal: You are on a branch yet to be born


In [15]:
!git add .


error: 'Prediction-Regression-Pytorch/' does not have a commit checked out
fatal: adding files failed


In [17]:
!git commit Prediction-Regression-Pytorch

error: pathspec 'Prediction-Regression-Pytorch' did not match any file(s) known to git
